<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
//*Para insertar datos en mas de una tabla en un mismo seeder
/**
 * Importar MODELOS de las tablas que queremos poblar e insertar datos
 * para cada una de ellas.
**/
// use App\Models\Departamento;
use App\Models\Region;
use App\Models\Ubicacion;
use App\Models\Grupo;
use App\Models\Escalafon;
use App\Models\Grado;
use App\Models\CalidadJuridica;
use App\Models\Sexo;
use App\Models\Comuna;
use App\Models\DireccionRegional;
use App\Models\Resolucion;
use App\Models\Cargo;

class CamposUsuarioNormalizados extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //* Insertamos datos en la tablas con el metodo INSERT
        // Población de la tabla 'departamento'
        // Departamento::insert([
        //     ['ID_DEPART' => 1, 'DEPARTAMENTO' => 'DEPARTAMENTO DE FISCALIZACION'],
        //     ['ID_DEPART' => 2, 'DEPARTAMENTO' => 'DEPARTAMENTO ASISTENCIA AL CONTRIBUYENTE'],
        //     ['ID_DEPART' => 3, 'DEPARTAMENTO' => 'DEPARTAMENTO DE AVALUACIONES'],
        //     ['ID_DEPART' => 4, 'DEPARTAMENTO' => 'DEPARTAMENTO JURIDICO'],
        // ]);
        // Población de la tabla 'region'
        /*Region::insert([
            ['ID_REGION' => 1, 'REGION' => 'REGIÓN DE ARICA Y PARINACOTA'],
            ['ID_REGION' => 2, 'REGION' => 'REGIÓN DE TARAPACÁ'],
            ['ID_REGION' => 3, 'REGION' => 'REGIÓN DE ANTOFAGASTA'],
            ['ID_REGION' => 4, 'REGION' => 'REGIÓN DE ATACAMA'],
            ['ID_REGION' => 5, 'REGION' => 'REGIÓN DE COQUIMBO'],
            ['ID_REGION' => 6, 'REGION' => 'REGIÓN DE VALPARAÍSO'],
            ['ID_REGION' => 7, 'REGION' => 'REGIÓN METROPOLITANA DE SANTIAGO'],
            ['ID_REGION' => 8, 'REGION' => 'REGIÓN DEL LIBERTADOR GENERAL BERNARDO O`HIGGINS'],
            ['ID_REGION' => 9, 'REGION' => 'REGIÓN DEL MAULE'],
            ['ID_REGION' => 10, 'REGION' => 'REGIÓN DE ÑUBLE'],
            ['ID_REGION' => 11, 'REGION' => 'REGIÓN DEL BIOBÍO'],
            ['ID_REGION' => 12, 'REGION' => 'REGIÓN DE LA ARAUCANÍA'],
            ['ID_REGION' => 13, 'REGION' => 'REGIÓN DE LOS RÍOS'],
            ['ID_REGION' => 14, 'REGION' => 'REGIÓN DE LOS LAGOS'],
            ['ID_REGION' => 15, 'REGION' => 'REGIÓN DE AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO'],
            ['ID_REGION' => 16, 'REGION' => 'REGIÓN DE MAGALLANES Y DE LA ANTÁRTICA CHILENA'],
        ]);*/
        /*//Población de la tabla 'direcciones_regionales'
        DireccionRegional::insert([
            ['ID_DIRECCION' => 1, 'DIRECCION' => 'DIRECCION REGIONAL DE ARICA', 'ID_REGION' => 1],
            ['ID_DIRECCION' => 2, 'DIRECCION' => 'OFICINA ALTO HOSPICIO', 'ID_REGION' => 2],
            ['ID_DIRECCION' => 3, 'DIRECCION' => 'DIRECCION REGIONAL DE IQUIQUE', 'ID_REGION' => 2],
            ['ID_DIRECCION' => 4, 'DIRECCION' => 'DIRECCION REGIONAL DE ANTOFAGASTA', 'ID_REGION' => 3],
            ['ID_DIRECCION' => 5, 'DIRECCION' => 'DIRECCION REGIONAL DE COPIAPO', 'ID_REGION' => 4],
            ['ID_DIRECCION' => 6, 'DIRECCION' => 'DIRECCION REGIONAL DE LA SERENA', 'ID_REGION' => 5],
            ['ID_DIRECCION' => 7, 'DIRECCION' => 'DIRECCION REGIONAL DE VALPARAISO', 'ID_REGION' => 6],
            ['ID_DIRECCION' => 8, 'DIRECCION' => 'DIRECCION NACIONAL', 'ID_REGION' => 7],
            ['ID_DIRECCION' => 9, 'DIRECCION' => 'DIRECCION REGIONAL METROPOLITANA SANTIAGO PONIENTE', 'ID_REGION' => 7],
            ['ID_DIRECCION' => 10, 'DIRECCION' => 'DIRECCION REGIONAL METROPOLITANA SANTIAGO SUR', 'ID_REGION' => 7],
            ['ID_DIRECCION' => 11, 'DIRECCION' => 'DIRECCION REGIONAL METROPOLITANA SANTIAGO NORTE', 'ID_REGION' => 7],
            ['ID_DIRECCION' => 12, 'DIRECCION' => 'DIRECCION REGIONAL METROPOLITANA SANTIAGO ORIENTE', 'ID_REGION' => 7],
            ['ID_DIRECCION' => 13, 'DIRECCION' => 'DIRECCION REGIONAL METROPOLITANA SANTIAGO CENTRO', 'ID_REGION' => 7],
            ['ID_DIRECCION' => 14, 'DIRECCION' => 'DIRECCION REGIONAL DE RANCAGUA', 'ID_REGION' => 8],
            ['ID_DIRECCION' => 15, 'DIRECCION' => 'DIRECCION REGIONAL DE TALCA', 'ID_REGION' => 9],
            ['ID_DIRECCION' => 16, 'DIRECCION' => 'DIRECCION REGIONAL DE CHILLAN', 'ID_REGION' => 10],
            ['ID_DIRECCION' => 17, 'DIRECCION' => 'DIRECCION REGIONAL DE CONCEPCION', 'ID_REGION' => 11],
            ['ID_DIRECCION' => 18, 'DIRECCION' => 'DIRECCION REGIONAL DE TEMUCO', 'ID_REGION' => 12],
            ['ID_DIRECCION' => 19, 'DIRECCION' => 'DIRECCION REGIONAL DE VALDIVIA', 'ID_REGION' => 13],
            ['ID_DIRECCION' => 20, 'DIRECCION' => 'DIRECCION REGIONAL DE PUERTO MONTT', 'ID_REGION' => 14],
            ['ID_DIRECCION' => 21, 'DIRECCION' => 'DIRECCION REGIONAL DE COYHAIQUE', 'ID_REGION' => 15],
            ['ID_DIRECCION' => 22, 'DIRECCION' => 'DIRECCION REGIONAL DE PUNTA ARENAS', 'ID_REGION' => 16]
            /*['ID_DIRECCION' => 1, 'DIRECCION' => 'DIRECCION REGIONAL DE ARICA'],
            ['ID_DIRECCION' => 2, 'DIRECCION' => 'OFICINA ALTO HOSPICIO'],
            ['ID_DIRECCION' => 3, 'DIRECCION' => 'DIRECCION REGIONAL DE IQUIQUE'],
            ['ID_DIRECCION' => 4, 'DIRECCION' => 'DIRECCION REGIONAL DE ANTOFAGASTA'],
            ['ID_DIRECCION' => 5, 'DIRECCION' => 'UNIDAD DE CALAMA'],
            ['ID_DIRECCION' => 6, 'DIRECCION' => 'UNIDAD DE TOCOPILLA'],
            ['ID_DIRECCION' => 7, 'DIRECCION' => 'UNIDAD DE TAL-TAL'],
            ['ID_DIRECCION' => 8, 'DIRECCION' => 'UNIDAD DE VALLENAR'],
            ['ID_DIRECCION' => 9, 'DIRECCION' => 'DIRECCION REGIONAL DE COPIAPO'],
            ['ID_DIRECCION' => 10, 'DIRECCION' => 'UNIDAD DE CHAÑARAL'],
            ['ID_DIRECCION' => 11, 'DIRECCION' => 'UNIDAD REGIONAL DE LA SERENA'],
            ['ID_DIRECCION' => 12, 'DIRECCION' => 'UNIDAD DE ILLAPEL'],
            ['ID_DIRECCION' => 13, 'DIRECCION' => 'UNIDAD DE OVALLE'],
            ['ID_DIRECCION' => 14, 'DIRECCION' => 'UNIDAD DE COQUIMBO'],
            ['ID_DIRECCION' => 15, 'DIRECCION' => 'UNIDAD DE SAN ANTONIO'],
            ['ID_DIRECCION' => 16, 'DIRECCION' => 'UNIDAD DE LA LIGUA'],
            ['ID_DIRECCION' => 17, 'DIRECCION' => 'UNIDAD DE LOS ANDES'],
            ['ID_DIRECCION' => 18, 'DIRECCION' => 'UNIDAD DE SAN ANTONIO'],
            ['ID_DIRECCION' => 19, 'DIRECCION' => 'DIRECCION REGIONAL DE VALPARAISO'],
            ['ID_DIRECCION' => 20, 'DIRECCION' => 'UNIDAD DE SAN FELIPE'],
            ['ID_DIRECCION' => 21, 'DIRECCION' => 'UNIDAD DE VIÑA DEL MAR'],
            ['ID_DIRECCION' => 22, 'DIRECCION' => 'UNIDAD DE QUILLOTA'],
            ['ID_DIRECCION' => 23, 'DIRECCION' => 'VILLA ALEMANA'],
            ['ID_DIRECCION' => 24, 'DIRECCION' => 'UNIDAD DE MELIPILLA'],
            ['ID_DIRECCION' => 25, 'DIRECCION' => 'UNIDAD DE BUIN'],
            ['ID_DIRECCION' => 26, 'DIRECCION' => 'UNIDAD DE SAN BERNARDO'],
            ['ID_DIRECCION' => 27, 'DIRECCION' => 'UNIDAD DE MAIPU'],
            ['ID_DIRECCION' => 28, 'DIRECCION' => 'DIRECCION REGIONAL SANTIAGO PONIENTE'],
            ['ID_DIRECCION' => 29, 'DIRECCION' => 'DIRECCION REGIONAL SANTIAGO NORTE'],
            ['ID_DIRECCION' => 30, 'DIRECCION' => 'DIRECCION REGIONAL SANTIAGO SUR'],
            ['ID_DIRECCION' => 31, 'DIRECCION' => 'UNIDAD DE LA FLORIDA'],
            ['ID_DIRECCION' => 32, 'DIRECCION' => 'UNIDAD DE ÑUÑOA'],
            ['ID_DIRECCION' => 33, 'DIRECCION' => 'DIRECCION REGIONAL SANTIAGO ORIENTE'],
            ['ID_DIRECCION' => 34, 'DIRECCION' => 'UNIDAD DE SAN FERNANDO'],
            ['ID_DIRECCION' => 35, 'DIRECCION' => 'UNIDAD DE SANTA CRUZ'],
            ['ID_DIRECCION' => 36, 'DIRECCION' => 'DIRECCION REGIONAL RANCAGUA'],
            ['ID_DIRECCION' => 37, 'DIRECCION' => 'UNIDAD DE PICHILEMU'],
            ['ID_DIRECCION' => 38, 'DIRECCION' => 'UNIDAD DE SAN VICENTE DE TAGUA TAGUA'],
            ['ID_DIRECCION' => 39, 'DIRECCION' => 'UNIDAD DE CAUQUENES'],
            ['ID_DIRECCION' => 40, 'DIRECCION' => 'UNIDAD DE LINARES'],
            ['ID_DIRECCION' => 50, 'DIRECCION' => 'UNIDAD DE CONSTITUCION'],
            ['ID_DIRECCION' => 51, 'DIRECCION' => 'DIRECCION REGIONAL DE TALCA'],
            ['ID_DIRECCION' => 52, 'DIRECCION' => 'UNIDAD DE CURICO'],
            ['ID_DIRECCION' => 53, 'DIRECCION' => 'UNIDAD DE PARRAL'],
            ['ID_DIRECCION' => 54, 'DIRECCION' => 'DIRECCION REGIONAL DE CHILLAN'],
            ['ID_DIRECCION' => 55, 'DIRECCION' => 'UNIDAD DE SAN CARLOS'],
            ['ID_DIRECCION' => 56, 'DIRECCION' => 'UNIDAD DE LOS ANGELES'],
            ['ID_DIRECCION' => 57, 'DIRECCION' => 'DIRECCION REGIONAL CONCEPCION'],
            ['ID_DIRECCION' => 58, 'DIRECCION' => 'LOCALIDAD DE CAÑETE'],
            ['ID_DIRECCION' => 59, 'DIRECCION' => 'UNIDAD DE LEBU'],
            ['ID_DIRECCION' => 60, 'DIRECCION' => 'UNIDAD DE TALCAHUANO'],
            ['ID_DIRECCION' => 61, 'DIRECCION' => 'UNIDAD DE ANGOL'],
            ['ID_DIRECCION' => 62, 'DIRECCION' => 'DIRECCION REGIONAL DE TEMUCO'],
            ['ID_DIRECCION' => 63, 'DIRECCION' => 'UNIDAD DE VICTORIA'],
            ['ID_DIRECCION' => 64, 'DIRECCION' => 'UNIDAD DE VILLARRICA'],
            ['ID_DIRECCION' => 65, 'DIRECCION' => 'DIRECCION REGIONAL VALDIVIA'],
            ['ID_DIRECCION' => 66, 'DIRECCION' => 'UNIDAD DE LA UNION'],
            ['ID_DIRECCION' => 67, 'DIRECCION' => 'UNIDAD DE LANCO'],
            ['ID_DIRECCION' => 68, 'DIRECCION' => 'UNIDAD DE PANGUIPULLI'],
            ['ID_DIRECCION' => 69, 'DIRECCION' => 'UNIDAD ANCUD'],
            ['ID_DIRECCION' => 70, 'DIRECCION' => 'UNIDAD PUERTO MONTT'],
            ['ID_DIRECCION' => 71, 'DIRECCION' => 'UNIDAD CASTRO'],
            ['ID_DIRECCION' => 72, 'DIRECCION' => 'OFICINA DE CHAITEN'],
            ['ID_DIRECCION' => 73, 'DIRECCION' => 'UNIDAD DE PUERTO VARAS'],
            ['ID_DIRECCION' => 74, 'DIRECCION' => 'UNIDAD DE OSORNO'],
            ['ID_DIRECCION' => 75, 'DIRECCION' => 'UNIDAD DE AYSEN'],
            ['ID_DIRECCION' => 76, 'DIRECCION' => 'UNIDAD DE CHILE CHICO'],
            ['ID_DIRECCION' => 77, 'DIRECCION' => 'OFICINA DE COCHRANE'],
            ['ID_DIRECCION' => 78, 'DIRECCION' => 'DIRECCION REGIONAL COYHAIQUE'],
            ['ID_DIRECCION' => 79, 'DIRECCION' => 'DIRECCION REGIONAL PUNTA ARENAS'],
            ['ID_DIRECCION' => 80, 'DIRECCION' => 'UNIDAD DE PORVENIR'],
            ['ID_DIRECCION' => 81, 'DIRECCION' => 'UNIDAD DE PUERTO NATALES']
        ]);*/
        // Población de la tabla 'ubicacion'
        /*Ubicacion::insert([
            
            SE ASOCIAN CON DEPARTAMENTOS LAS ANTIGÜAS TUPLAS DE UBICACION:
            ['ID_UBICACION' => 1, 'UBICACION' => 'GABINETE DIRECTOR'],
            ['ID_UBICACION' => 2, 'UBICACION' => 'DEPARTAMENTO DE ADMINISTRACIÓN'],
            ['ID_UBICACION' => 3, 'UBICACION' => 'DEPARTAMENTO DE FISCALIZACIÓN'],
            ['ID_UBICACION' => 4, 'UBICACION' => 'DEPARTAMENTO DE ASISTENCIA AL CONTRIBUYENTE'],
            ['ID_UBICACION' => 5, 'UBICACION' => 'DEPARTAMENTO DE AVALUACIONES'],
            ['ID_UBICACION' => 6, 'UBICACION' => 'UNIDAD DE LOS ÁNGELES'],
            ['ID_UBICACION' => 7, 'UBICACION' => 'UNIDAD DE LEBU'],
            ['ID_UBICACION' => 8, 'UBICACION' => 'UNIDAD DE TALCAHUANO'],
            ['ID_UBICACION' => 9, 'UBICACION' => 'DEPARTAMENTO DE PROCEDIMIENTOS ADMINISTRATIVOS TRIBUTARIOS'],
            ['ID_UBICACION' => 10, 'UBICACION' => 'DEPARTAMENTO JURÍDICO'],
            ['ID_UBICACION' => 99, 'UBICACION' => 'DIRECCION NACIONAL'],
            ['ID_UBICACION' => 999, 'UBICACION' => 'EXTERNO']
        
        ]); */
        /*
        $dataUbicacion = [
            [1, 'DIRECCION REGIONAL DE ARICA', 1],
            [2, 'UNIDAD ALTO HOSPICIO', 2],
            [3, 'DIRECCION REGIONAL DE IQUIQUE', 2],
            [4, 'DIRECCION REGIONAL DE ANTOFAGASTA', 3],
            [5, 'UNIDAD DE CALAMA', 3],
            [6, 'UNIDAD DE TOCOPILLA', 3],
            [7, 'UNIDAD DE VALLENAR', 4],
            [8, 'DIRECCION REGIONAL DE COPIAPO', 4],
            [9, 'UNIDAD DE CHAÑARAL', 4],
            [10, 'DIRECCION REGIONAL DE LA SERENA', 5],
            [11, 'UNIDAD DE ILLAPEL', 5],
            [12, 'UNIDAD DE OVALLE', 5],
            [13, 'UNIDAD DE COQUIMBO', 5],
            [14, 'UNIDAD DE SAN ANTONIO', 6],
            [15, 'UNIDAD DE LA LIGUA', 6],
            [16, 'UNIDAD DE LOS ANDES', 6],
            [17, 'DIRECCION NACIONAL', 7],
            [18, 'DIRECCION REGIONAL DE VALPARAISO', 6],
            [19, 'UNIDAD DE SAN FELIPE', 6],
            [20, 'UNIDAD DE VIÑA DEL MAR', 6],
            [21, 'UNIDAD DE QUILLOTA', 6],
            [22, 'UNIDAD DE VILLA ALEMANA', 6],
            [23, 'UNIDAD DE BUIN', 9],
            [24, 'UNIDAD DE SAN BERNARDO', 9],
            [25, 'UNIDAD DE MAIPU', 8],
            [26, 'DIRECCION REGIONAL SANTIAGO PONIENTE', 8],
            [27, 'DIRECCION REGIONAL SANTIAGO NORTE', 10],
            [28, 'DIRECCION REGIONAL SANTIAGO SUR', 9],
            [29, 'UNIDAD DE LA FLORIDA', 9],
            [30, 'CENTRAL DE TIMBRAJE', 12],
            [31, 'UNIDAD DE ÑUÑOA', 12],
            [32, 'DIRECCION REGIONAL SANTIAGO ORIENTE', 11],
            [33, 'UNIDAD DE SAN FERNANDO', 13],
            [34, 'UNIDAD DE SANTA CRUZ', 13],
            [35, 'DIRECCION REGIONAL DE RANCAGUA', 13],
            [36, 'UNIDAD DE PICHILEMU', 13],
            [37, 'UNIDAD DE SAN VICENTE DE TAGUA TAGUA', 13],
            [38, 'UNIDAD DE CAUQUENES', 14],
            [39, 'UNIDAD DE LINARES', 14],
            [40, 'UNIDAD DE CONSTITUCION', 14],
            [41, 'DIRECCION REGIONAL DE TALCA', 14],
            [42, 'UNIDAD DE CURICO', 14],
            [43, 'UNIDAD DE PARRAL', 14],
            [44, 'DIRECCION REGIONAL DE CHILLAN', 15],
            [45, 'UNIDAD DE SAN CARLOS', 15],
            [46, 'UNIDAD DE LOS ANGELES', 16],
            [47, 'DIRECCION REGIONAL CONCEPCION', 16],
            [48, 'UNIDAD DE LEBU', 16],
            [49, 'UNIDAD DE MELIPILLA', 8],
            [50, 'UNIDAD DE TALCAHUANO', 16],
            [51, 'UNIDAD DE ANGOL', 17],
            [52, 'DIRECCION RAGIONAL DE TEMUCO', 17],
            [53, 'UNIDAD DE VICTORIA', 17],
            [54, 'UNIDAD DE VILLARRICA', 17],
            [55, 'DIRECCION RAGIONAL VALDIVIA', 18],
            [56, 'UNIDAD DE LA UNION', 18],
            [57, 'UNIDAD DE LANCO', 18],
            [58, 'UNIDAD DE PANGUIPULLI', 18],
            [59, 'UNIDAD DE ANCUD', 19],
            [60, 'DIRECCION REGIONAL PUERTO MONTT', 19],
            [61, 'UNIDAD CASTRO', 19],
            [62, 'UNIDAD DE CHAITEN', 19],
            [63, 'UNIDAD DE PUERTO VARAS', 19],
            [64, 'UNIDAD DE OSORNO', 19],
            [65, 'UNIDAD DE AYSEN', 20],
            [66, 'UNIDAD DE CHILE CHICO', 20],
            [67, 'DIRECCION REGIONAL COYHAIQUE', 20],
            [68, 'DIRECCION REGIONAL PUNTA ARENAS', 21],
            [69, 'UNIDAD DE PUERTO NATALES', 21],
            [70, 'UNIDAD DE PORVENIR', 21]
        ];

        Ubicacion::insert($dataUbicacion);*/

           
        // Población de la tabla 'grupo'
        Grupo::insert([
            ['ID_GRUPO' => 1, 'GRUPO' => 'GRUPO N°1 FISCALIZACIÓN'],
            ['ID_GRUPO' => 2, 'GRUPO' => 'GRUPO N°2 FISCALIZACIÓN'],
            ['ID_GRUPO' => 3, 'GRUPO' => 'GRUPO N°3 FISCALIZACIÓN'],
            ['ID_GRUPO' => 4, 'GRUPO' => 'GRUPO N°4 FISCALIZACIÓN'],
            ['ID_GRUPO' => 5, 'GRUPO' => 'GRUPO N°5 FISCALIZACIÓN'],
            ['ID_GRUPO' => 6, 'GRUPO' => 'GRUPO N°6 FISCALIZACIÓN'],
            ['ID_GRUPO' => 7, 'GRUPO' => 'GRUPO N°7 FISCALIZACIÓN'],
            ['ID_GRUPO' => 8, 'GRUPO' => 'GRUPO N°1 AVALUACIONES'],
            ['ID_GRUPO' => 9, 'GRUPO' => 'GRUPO N°2 AVALUACIONES'],
            ['ID_GRUPO' => 10, 'GRUPO' => 'GRUPO N°1 ATENCIÓN DE CONTRIBUYENTES'],
            ['ID_GRUPO' => 11, 'GRUPO' => 'GRUPO N°2 ATENCIÓN DE CONTRIBUYENTES'],
            ['ID_GRUPO' => 12, 'GRUPO' => 'GRUPO N°1 INFORMACIÓN Y ASISTENCIA'],
            ['ID_GRUPO' => 13, 'GRUPO' => 'GRUPO N°1 ATENCIÓN Y ASISTENCIA'],
            ['ID_GRUPO' => 14, 'GRUPO' => 'GRUPO CUMPLIMIENTO TRIBUTARIO EN TERRENO'],
            ['ID_GRUPO' => 15, 'GRUPO' => 'GRUPO AVALUACIONES'],
        ]);
        // Población de la tabla 'escalafon'
        Escalafon::insert([
            ['ID_ESCALAFON' => 1, 'ESCALAFON' => 'TECNICO EN FISCALIZACION'],
            ['ID_ESCALAFON' => 2, 'ESCALAFON' => 'ADMINISTRATIVO'],
            ['ID_ESCALAFON' => 3, 'ESCALAFON' => 'FISCALIZADOR TRIBUTARIO'],
            ['ID_ESCALAFON' => 4, 'ESCALAFON' => 'PROFESIONAL'],
            ['ID_ESCALAFON' => 5, 'ESCALAFON' => 'DIRECTIVO'],
            ['ID_ESCALAFON' => 6, 'ESCALAFON' => 'AUXILIAR'],
            ['ID_ESCALAFON' => 7, 'ESCALAFON' => 'TECNICO EN INFORMATICA'],
            ['ID_ESCALAFON' => 8, 'ESCALAFON' => 'TECNICO EN AVALUACIONES'],
            ['ID_ESCALAFON' => 9, 'ESCALAFON' => 'FISCALIZADOR TRASADOR'],
        ]);
        // Población de la tabla 'grado'
        Grado::insert([
            ['ID_GRADO' => 1, 'GRADO' => 4],
            ['ID_GRADO' => 2, 'GRADO' => 7],
            ['ID_GRADO' => 3, 'GRADO' => 8],
            ['ID_GRADO' => 4, 'GRADO' => 9],
            ['ID_GRADO' => 5, 'GRADO' => 10],
            ['ID_GRADO' => 6, 'GRADO' => 11],
            ['ID_GRADO' => 7, 'GRADO' => 12],
            ['ID_GRADO' => 8, 'GRADO' => 13],
            ['ID_GRADO' => 9, 'GRADO' => 14],
            ['ID_GRADO' => 10, 'GRADO' => 15],
            ['ID_GRADO' => 11, 'GRADO' => 16],
            ['ID_GRADO' => 12, 'GRADO' => 17],
            ['ID_GRADO' => 13, 'GRADO' => 18],
            ['ID_GRADO' => 14, 'GRADO' => 19],
            ['ID_GRADO' => 15, 'GRADO' => 20],
            ['ID_GRADO' => 16, 'GRADO' => 21],
        ]);
        Cargo::insert([
            ['ID_CARGO' => 1, 'CARGO' => 'DIRECTOR REGIONAL'],
            ['ID_CARGO' => 2, 'CARGO' => 'JEFE DE DEPARTAMENTO JURIDICO'],
            ['ID_CARGO' => 3, 'CARGO' => 'JEFE DE DEPARTAMENTO DE FISCALIZACION'],
            ['ID_CARGO' => 4, 'CARGO' => 'JEFE DE DEPARTAMENTO DE ASISTENCIA'],
            ['ID_CARGO' => 5, 'CARGO' => 'JEFE DE DEPARTAMENTO DE AVALUACIONES'],
            ['ID_CARGO' => 6, 'CARGO' => 'JEFE DE DEPARTAMENTO DE PROCEDIMIENTOS ADMINISTRATIVOS'],
            ['ID_CARGO' => 7, 'CARGO' => 'JEFE DE ADMINISTRACION'],
            ['ID_CARGO' => 8, 'CARGO' => 'JEFE DE UNIDAD DE TALCAHUANO'],
            ['ID_CARGO' => 9, 'CARGO' => 'JEFE DE UNIDAD DE LOS ANGELES'],
            ['ID_CARGO' => 10, 'CARGO' => 'JEFE DE UNIDAD DE LEBU'],
            ['ID_CARGO' => 11, 'CARGO' => 'JEFE DE GRUPO CONCEPCION 1'],
            ['ID_CARGO' => 12, 'CARGO' => 'JEFE DE GRUPO CONCEPCION 2'],
            ['ID_CARGO' => 13, 'CARGO' => 'JEFE DE GRUPO CONCEPCION 3'],
            ['ID_CARGO' => 14, 'CARGO' => 'JEFE DE GRUPO CONCEPCION 4'],
            ['ID_CARGO' => 15, 'CARGO' => 'JEFE DE GRUPO CONCEPCION 5'],
            ['ID_CARGO' => 16, 'CARGO' => 'JEFE DE GRUPO CONCEPCION 6'],
            ['ID_CARGO' => 17, 'CARGO' => 'JEFE DE GRUPO CONCEPCION 7'],
            ['ID_CARGO' => 18, 'CARGO' => 'JEFE DE GRUPO CUMPLIMIENTO TRIBUTARIO EN TERRENO'],
            ['ID_CARGO' => 19, 'CARGO' => 'JEFE GRUPO N° 1 MEDIANAS Y GRANDES EMPRESAS SEDE REGIONAL CONCEPCION'],
            ['ID_CARGO' => 20, 'CARGO' => 'JEFE GRUPO N° 2 MEDIANAS Y GRANDES EMPRESAS SEDE REGIONAL CONCEPCION'],
            ['ID_CARGO' => 21, 'CARGO' => 'JEFE GRUPO N° 3 MEDIANAS Y GRANDES EMPRESAS SEDE REGIONAL CONCEPCION'],
            ['ID_CARGO' => 22, 'CARGO' => 'JEFE GRUPO N° 1 PERSONAS Y MICRO-PEQUEÑA EMPRESAS SEDE REGIONAL CONCEPCION'],
            ['ID_CARGO' => 23, 'CARGO' => 'JEFE GRUPO N° 2 PERSONAS Y MICRO-PEQUEÑA EMPRESAS SEDE REGIONAL CONCEPCION'],
            ['ID_CARGO' => 24, 'CARGO' => 'JEFE GRUPO N° 3 PERSONAS Y MICRO-PEQUEÑA EMPRESAS SEDE REGIONAL CONCEPCION'],
            ['ID_CARGO' => 25, 'CARGO' => 'JEFE GRUPO N° 4 PERSONAS Y MICRO-PEQUEÑA EMPRESAS SEDE REGIONAL CONCEPCION'],
            ['ID_CARGO' => 26, 'CARGO' => 'JEFE GRUPO N° 1 FISCALIZACION UNIDAD DE CHILLAN'],
            ['ID_CARGO' => 27, 'CARGO' => 'JEFE GRUPO N° 2 FISCALIZACION UNIDAD DE CHILLAN'],
            ['ID_CARGO' => 28, 'CARGO' => 'JEFE GRUPO N° 1 FISCALIZACION UNIDAD DE LOS ANGELES'],
            ['ID_CARGO' => 29, 'CARGO' => 'JEFE GRUPO N° 2 FISCALIZACION UNIDAD DE LOS ANGELES'],
            ['ID_CARGO' => 30, 'CARGO' => 'JEFE GRUPO N° 1 FISCALIZACION TALCAHUANO'],
            ['ID_CARGO' => 31, 'CARGO' => 'JEFE DE UNIDAD DE CHILLAN'],
            ['ID_CARGO' => 32, 'CARGO' => 'JEFE DE UNIDAD DE SAN CARLOS'],
            ['ID_CARGO' => 99, 'CARGO' => 'FUNCIONARIO'],
            ['ID_CARGO' => 999, 'CARGO' => 'EXTERNO']
        ]);
        // Población de la tabla 'calidad_juridica'
        CalidadJuridica::insert([
            ['ID_CALIDAD' => 1, 'CALIDAD' => 'PLANTA'],
            ['ID_CALIDAD' => 2, 'CALIDAD' => 'CONTRATA'],
            ['ID_CALIDAD' => 3, 'CALIDAD' => 'OTROS'],
        ]);
        // Población de la tabla 'sexo'
        Sexo::insert([
            ['ID_SEXO' => 1, 'SEXO' => 'MASCULINO'],
            ['ID_SEXO' => 2, 'SEXO' => 'FEMENINO'],
        ]);
        /*//Población de la tabla 'comunas'
        $dataComuna = [
            [1, 'Arica', 1],
            [2, 'Camarones', 1],
            [3, 'Putre', 1],
            [4, 'General Lagos', 1],
            [5, 'Iquique', 2],
            [6, 'Alto Hospicio', 2],
            [7, 'Pozo Almonte', 2],
            [8, 'Camiña', 2],
            [9, 'Colchane', 2],
            [10, 'Huara', 2],
            [11, 'Pica', 2],
            [12, 'Antofagasta', 3],
            [13, 'Mejillones', 3],
            [14, 'Sierra Gorda', 3],
            [15, 'Tal tal', 3],
            [16, 'Calama', 3],
            [17, 'Ollagüe', 3],
            [18, 'San Pedro de Atacama', 3],
            [19, 'María Elena', 3],
            [20, 'Tocopilla', 3],
            [21, 'Copiapó', 4],
            [22, 'Caldera', 4],
            [23, 'Tierra Amarilla', 4],
            [24, 'Chañaral', 4],
            [25, 'Diego de Almagro', 4],
            [26, 'Vallenar', 4],
            [27, 'Alto del Carmen', 4],
            [28, 'Freirina', 4],
            [29, 'Huasco', 4],
            [30, 'La Serena', 5],
            [31, 'Coquimbo', 5],
            [32, 'Andacollo', 5],
            [33, 'La Higuera', 5],
            [34, 'Paiguano', 5],
            [35, 'Vicuña', 5],
            [36, 'Illapel', 5],
            [37, 'Canela', 5],
            [38, 'Los Vilos', 5],
            [39, 'Salamanca', 5],
            [40, 'Ovalle', 5],
            [41, 'Combarbalá', 5],
            [42, 'Monte Patria', 5],
            [43, 'Punitaqui', 5],
            [44, 'Río Hurtado', 5],
            [45, 'Valparaíso', 6],
            [46, 'Casablanca', 6],
            [47, 'Concón', 6],
            [48, 'Juan Fernández', 6],
            [49, 'Puchuncaví', 6],
            [50, 'Quilpué', 6],
            [51, 'Quintero', 6],
            [52, 'Villa Alemana', 6],
            [53, 'Viña del Mar', 6],
            [54, 'Zapallar', 6],
            [55, 'La Ligua', 6],
            [56, 'Papudo', 6],
            [57, 'Petorca', 6],
            [58, 'Cabildo', 6],
            [59, 'Calle Larga',6],
            [60, 'Los Andes', 6],
            [61, 'Rinconada', 6],
            [62, 'San Esteban', 6],
            [63, 'La Calera', 6],
            [64, 'Hijuelas', 6],
            [65, 'La Cruz', 6],
            [66, 'Nogales', 6],
            [67, 'Quillota', 6],
            [68, 'La Calera', 6],
            [69, 'Limache', 6],
            [70, 'Olmue', 6],
            [71, 'Cerrillos', 7],
            [72, 'Cerro Navia', 7],
            [73, 'Conchalí', 7],
            [74, 'El Bosque', 7],
            [75, 'Estación Central', 7],
            [76, 'Huechuraba', 7],
            [77, 'Independencia', 7],
            [78, 'La Cisterna', 7],
            [79, 'La Florida', 7],
            [80, 'La Granja', 7],
            [81, 'La Pintana', 7],
            [82, 'La Reina', 7],
            [83, 'Las Condes', 7],
            [84, 'Lo Barnechea', 7],
            [85, 'Lo Espejo', 7],
            [86, 'Lo Prado', 7],
            [87, 'Macul', 7],
            [88, 'Maipú', 7],
            [89, 'Ñuñoa', 7],
            [90, 'Pedro Aguirre Cerda', 7],
            [91, 'Peñalolén', 7],
            [92, 'Providencia', 7],
            [93, 'Pudahuel', 7],
            [94, 'Puente Alto', 7],
            [95, 'Quilicura', 7],
            [96, 'Quinta Normal', 7],
            [97, 'Recoleta', 7],
            [98, 'Renca', 7],
            [99, 'San Bernardo', 7],
            [100, 'San Joaquín', 7],
            [101, 'San José de Maipo', 7],
            [102, 'San Miguel', 7],
            [103, 'San Pedro', 7],
            [104, 'San Ramón', 7],
            [105, 'Santiago Centro', 7],
            [106, 'Vitacura', 7],
            [107, 'Rancagua', 8],
            [108, 'Codegua', 8],
            [109, 'Coinco', 8],
            [110, 'Coltauco', 8],
            [111, 'Doñihue', 8],
            [112, 'Graneros', 8],
            [113, 'Las Cabras', 8],
            [114, 'Machalí', 8],
            [115, 'Malloa', 8],
            [117, 'Olivar', 8],
            [118, 'Peumo', 8],
            [119, 'Pichidegua', 8],
            [120, 'Quinta de Tilcoco', 8],
            [121, 'Rengo', 8],
            [122, 'Requínoa', 8],
            [123, 'San Vicente', 8],
            [124, 'Talca', 9],
            [125, 'Constitución', 9],
            [126, 'Curepto', 9],
            [127, 'Empedrado', 9],
            [128, 'Maule', 9],
            [129, 'Pelarco', 9],
            [130, 'Pencahue', 9],
            [131, 'Río Claro', 9],
            [132, 'San Clemente', 9],
            [133, 'San Rafael', 9],
            [134, 'Cauquenes', 9],
            [135, 'Chanco', 9],
            [136, 'Pelluhue', 9],
            [137, 'Curicó', 9],
            [138, 'Hualañé', 9],
            [139, 'Licantén', 9],
            [140, 'Molina', 9],
            [141, 'Rauco', 9],
            [142, 'Romeral', 9],
            [143, 'Sagrada Familia', 9],
            [144, 'Teno', 9],
            [145, 'Vichuquén', 9],
            [146, 'Linares', 9],
            [147, 'Colbún', 9],
            [148, 'Longaví', 9],
            [149, 'Parral', 9],
            [150, 'Retiro', 9],
            [151, 'San Javier', 9],
            [152, 'Villa Alegre', 9],
            [153, 'Yerbas Buenas', 9],
            [154, 'Chillán', 10],
            [155, 'Bulnes', 10],
            [156, 'Chillán Viejo', 10],
            [157, 'El Carmen', 10],
            [158, 'Pemuco', 10],
            [159, 'Pinto', 10],
            [160, 'Quillón', 10],
            [161, 'San Ignacio', 10],
            [162, 'Yungay', 10],
            [163, 'Cobquecura', 10],
            [164, 'Coelemu', 10],
            [165, 'Ninhue', 10],
            [166, 'Portezuelo', 10],
            [167, 'Quirihue', 10],
            [168, 'Ránquil', 10],
            [169, 'Treguaco', 10],
            [170, 'San Carlos', 10],
            [171, 'Coihueco', 10],
            [172, 'Ñiquén', 10],
            [173, 'San Fabián', 10],
            [174, 'San Nicolás', 10],
            [175, 'Concepción', 11],
            [176, 'Coronel', 11],
            [177, 'Chiguayante', 11],
            [178, 'Florida', 11],
            [179, 'Hualqui', 11],
            [180, 'Lota', 11],
            [181, 'Penco', 11],
            [182, 'San Pedro de la Paz', 11],
            [183, 'Santa Juana', 11],
            [184, 'Talcahuano', 11],
            [185, 'Tomé', 11],
            [186, 'Hualpén', 11],
            [187, 'Lebu', 11],
            [188, 'Arauco', 11],
            [189, 'Cañete', 11],
            [190, 'Contulmo', 11],
            [191, 'Curanilahue', 11],
            [192, 'Los Álamos', 11],
            [193, 'Tirúa', 11],
            [194, 'Los Ángeles', 11],
            [195, 'Antuco', 11],
            [196, 'Cabrero', 11],
            [197, 'Laja', 11],
            [198, 'Mulchén', 11],
            [199, 'Nacimiento', 11],
            [200, 'Negrete', 11],
            [201, 'Quilaco', 11],
            [202, 'Quilleco', 11],
            [203, 'San Rosendo', 11],
            [204, 'Santa Bárbara', 11],
            [205, 'Tucapel', 11],
            [206, 'Yumbel', 11],
            [207, 'Alto Biobío', 11],
            [208, 'Temuco', 12],
            [209, 'Carahue', 12],
            [210, 'Cunco', 12],
            [211, 'Curarrehue', 12],
            [212, 'Freire', 12],
            [213, 'Galvarino', 12],
            [214, 'Gorbea', 12],
            [215, 'Lautaro', 12],
            [216, 'Loncoche', 12],
            [217, 'Melipeuco', 12],
            [218, 'Nueva Imperial', 12],
            [219, 'Padre las Casas', 12],
            [220, 'Perquenco', 12],
            [221, 'Pitrufquén', 12],
            [222, 'Pucón', 12],
            [223, 'Saavedra', 12],
            [224, 'Teodoro Schmidt', 12],
            [225, 'Toltén', 12],
            [226, 'Vilcún', 12],
            [227, 'Villarrica', 12],
            [228, 'Cholchol', 12],
            [229, 'Angol', 12],
            [230, 'Collipulli', 12],
            [231, 'Curacautín', 12],
            [232, 'Ercilla', 12],
            [233, 'Lonquimay', 12],
            [234, 'Los Sauces', 12],
            [235, 'Lumaco', 12],
            [236, 'Purén', 12],
            [237, 'Renaico', 12],
            [238, 'Traiguén', 12],
            [239, 'Victoria', 12],
            [240, 'Valdivia', 13],
            [241, 'Corral', 13],
            [242, 'Lanco', 13],
            [243, 'Los Lagos', 13],
            [244, 'Máfil', 13],
            [245, 'Mariquina', 13],
            [246, 'Paillaco', 13],
            [247, 'Panguipulli', 13],
            [248, 'La Unión', 13],
            [249, 'Futrono', 13],
            [250, 'Lago Ranco', 13],
            [251, 'Río Bueno', 13],
            [252, 'Puerto Montt', 14],
            [253, 'Calbuco', 14],
            [254, 'Cochamó', 14],
            [255, 'Fresia', 14],
            [256, 'Frutillar', 14],
            [257, 'Los Muermos', 14],
            [258, 'Llanquihue', 14],
            [259, 'Maullín', 14],
            [260, 'Puerto Varas', 14],
            [261, 'Castro', 14],
            [262, 'Ancud', 14],
            [263, 'Chonchi', 14],
            [264, 'Curaco de Vélez', 14],
            [265, 'Dalcahue', 14],
            [266, 'Puqueldón', 14],
            [267, 'Queilén', 14],
            [268, 'Quellón', 14],
            [269, 'Quemchi', 14],
            [270, 'Quinchao', 14],
            [271, 'Osorno', 14],
            [272, 'Puerto Octay', 14],
            [273, 'Purranque', 14],
            [274, 'Puyehue', 14],
            [275, 'Río Negro', 14],
            [276, 'San Juan de la Costa', 14],
            [277, 'San Pablo', 14],
            [278, 'Coyhaique', 15],
            [279, 'Lago Verde', 15],
            [280, 'Aysén', 15],
            [281, 'Cisnes', 15],
            [282, 'Guaitecas', 15],
            [283, 'Cochrane', 15],
            [284, 'OHiggins', 15],
            [285, 'Tortel', 15],
            [286, 'Punta Arenas', 16],
            [287, 'Laguna Blanca', 16],
            [288, 'Río Verde', 16],
            [289, 'San Gregorio', 16],
            [290, 'Cabo de Hornos', 16],
            [292, 'Porvenir', 16],
            [293, 'Primavera', 16],
            [294, 'Timaukel', 16],
            [295, 'Puerto Natales', 16],
            [296, 'Torres del Paine', 16]           
        ];

        Comuna::insert($dataComuna);*/

    }
}
